Add Guttman Gamma Thermalisation
artis-mcrt/artis pull request #93
Opened 2024-06-18 13:48 UTC by gleck97

2024-06-20 08:10 UTC, lukeshingles requested changes
Just to make sure: the non-draft state of this PR means that you've run this code and the results seem sensible?

2024-06-20 08:10 UTC, lukeshingles commented on gammapkt.cc
> +  avg_column_density /= numb_rnd_dirs;  // calculate average here
A minor suggestion: With column_densities as a std::array, you can avoid having a mutable state of avg_columns_density:
`const double avg_column_density = std::accumulate(column_densities.cbegin(), column_densities.cend()) / std::ssize(column_densities);`

2024-06-20 08:36 UTC, gleck97 commented
> Just to make sure: the non-draft state of this PR means that you've run this code and the results seem sensible?

I sent you the plots on mattermost

2024-07-31 14:01 UTC, lukeshingles submitted a review, later dismissed

2024-07-31 14:06 UTC, lukeshingles submitted a review, later dismissed

2024-07-31 16:23 UTC, lukeshingles approved these changes

2024-07-31 16:52 UTC, merged